### ISSUE TITLE
doesnt compile on latest cohttp/irmin

### ISSUE THREAD

**Issue by avsm** [mirage/merge-queues#4]
From `is-mirage-broken`:

```
The following dependencies couldn't be met:
  - merge-queues -> irmin = 0.8.3 -> git = 1.2.0 -> conduit = 0.5.1
```

**Comment by samoht** [comment]
This requires some `mirage-tc` massaging (mainly https://github.com/mirage/mirage-tc/issues/7, the other changes are almost trivial).

And/or we need a `json` type-conv generator.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/3792
